<?php
	$acl = new Fonfonblog_Acl();
?>
<header>
	<h2><i class="fa fa-pencil-square-o"></i> <?php echo $this->escape($this->title); ?></h2>
	<hr />
</header>
<div class="list-group">
	<?php
		if (isset($this->error)) {
			echo $this->error;
		}
	?>
	<ul class="nav nav-tabs" style="margin-bottom: 15px;">
	  <li class="active"><a href="#frmEdit" data-toggle="tab">Editer</a></li>
	  <li><a href="#editMission" data-toggle="tab">Editer une mission</a></li>
	  <li><a href="#addMission" data-toggle="tab">Ajouter une mission</a></li>
	  <li><a href="#delMission" data-toggle="tab">Supprimer une mission</a></li>
	</ul>
	
	<div id="myTabContent" class="tab-content">
		
		<div class="tab-pane fade active in" id="frmEdit">
			<?php echo $this->formExperiences; ?>
		</div>
		
		<div class="tab-pane fade" id="editMission">
			<!-- header>
				<h3>Modifier une mission</h3><hr />
			</header -->
			<article>
				<p>
				<?php
				
					$btnDeleteMission = '<a type="button" href="" class="btn btn-primary btn-sm">Suppression mission</a>';
					
					if ($this->listeMissions != null) {
						$stbMission = new Zend_Form_Element_Select('choixMission');
						$stbMission->setLabel('Sélectionner une mission')
							->setOptions(array('class' => 'form-control'))
							->setMultiOptions($this->listeMissions)
							//->removeDecorator()
							;
						echo $stbMission;
						
						//echo $btnDeleteMission;
				?>
				</p>
				<hr>
				<?php
						$json = new Zend_Form_Element_Hidden("json_mission");
						$json->setValue($this->tabMissionsJson)
								->removeDecorator('Label');
						echo $json;
					}
					echo $this->formMissionEdit;
				?>
			</article>
		</div>
		
		<div class="tab-pane fade" id="addMission">
			<!-- header>
				<h3>Ajouter une mission</h3><hr />
			</header -->
			<article>
			<?php
				echo $this->formMissionAdd;
			?>
			</article>
		</div>
		
		<div class="tab-pane fade" id="delMission">
			<!-- header>
				<h3>Supprimer une mission</h3><hr />
			</header -->
			<article>
				<table class="table table-striped table-hover ">
					<thead>
						<tr>
							<th>Id</th>
							<th>Mission</th>
							<th>Actions</th>
						</tr>
					</thead>
					<tbody>
					<?php
						$ligneMission = "";
						foreach ($this->listeMissionsForDel as $idMission=>$mission) {
							$ligneMission .= '<tr>';
							$ligneMission .= '<td>' . $idMission . '</td>';
							$ligneMission .= '<td>' . $mission . '</td>';
							if ($acl->isAllowed(Zend_Auth::getInstance()->getStorage()->read()->roles, 'btnFormAdministration')) {
								$ligneMission .= '<td><a type="button" href="' . $this->linkDelMission . $idMission . '" class="btn btn-primary btn-xs">Supprimer</a></td>';
							} else {
								$ligneMission .= '<td><a type="button" href="#" class="btn btn-primary btn-xs">Supprimer</a></td>';
							}
							$ligneMission .= '</tr>';
						}
						echo $ligneMission;
					?>
					</tbody>
				</table>
			</article>
		</div>
	</div>
</div>