<header>
	<h2><?php echo $this->escape($this->title); ?></h2>
	<hr />
</header>
<div class="list-group">
	<?php
		if (isset($this->error)) {
			echo $this->error;
		}
	?>
	<ul class="nav nav-tabs" style="margin-bottom: 15px;">
	  <li class="active"><a href="#frmEdit" data-toggle="tab">Editer</a></li>
	  <li><a href="#editMission" data-toggle="tab">Editer une mission</a></li>
	  <li><a href="#addMission" data-toggle="tab">Ajouter une mission</a></li>
	</ul>
	
	<div id="myTabContent" class="tab-content">
		
		<div class="tab-pane fade active in" id="frmEdit">
			<?php echo $this->formExperiences; ?>
		</div>
		
		<div class="tab-pane fade" id="editMission">
			<header>
				<h3>Modifier une mission</h3><hr />
			</header>
			<article>
				<p>
				<?php
					if ($this->listeMissions != null) {
						$stbMission = new Zend_Form_Element_Select('choixMission');
						$stbMission->setLabel('Sélectionner une mission')
							->setOptions(array('class' => 'form-control'))
							->setMultiOptions($this->listeMissions);
						echo $stbMission;
				?>
				</p>
				<hr>
				<?php
						$json = new Zend_Form_Element_Hidden("json_mission");
						$json->setValue($this->tabMissionsJson)
								->removeDecorator('Label');
						echo $json;
					}
					echo $this->formMissionEdit;
					
					//$this->formMissionEdit->addElement($listeCompetences);
				?>
			</article>
		</div>
		
		<div class="tab-pane fade" id="addMission">
			<header>
				<h3>Ajouter une mission</h3><hr />
			</header>
			<article>
			<?php
				echo $this->formMissionAdd;
			?>
			</article>
		</div>
	</div>
</div>