<header>
	<h3><i class="fa fa-leaf"></i> A propos de moi</h3><hr>
</header>
<section>
	<p class="presentation">
		<img alt="profil" src="/img/profil.png">
		Bienvenue sur mon CV en ligne, je suis ingénieur d'études et développement, basé à Montpellier (34) dans le sud de la France et âgé de 30 ans.
	</p>
	<br>
	<p class="presentation">Passionné par l'informatique depuis plusieurs années, 
	j'ai pris la résolution à l’issue de mes études de m'orienter vers les technologies Web afin de combiner orientation et aspirations professionnelles avec passion personnelle. 
	Ayant appris par moi-même le PHP, HTML/CSS, le javascript etc., 
	j'aspire avant tout à apprendre et me perfectionner continuellement, tout en découvrant l'évolution perpétuelle et les nouveautés que ce domaine m'offre.
	</p>
</section>