<header>
	<h2><?php echo $this->escape($this->title); ?></h2>
	<hr />
</header>
<div class="list-group">
	<a type="button" href="<?php echo $this->linkAdd; ?>" class="btn btn-primary btn-sm">Ajouter une compétence</a>
	<?php
		if (isset($this->error)) {
			echo $this->error;
		}
		
		if (isset($this->message)) {
			echo $this->message;
		}
	?>
	<table class="table table-striped table-hover ">
		<thead>
			<tr>
				<th>Id</th>
				<th>Compétence</th>
				<th>Compétence principale</th>
				<th colspan="2">Actions</th>
			</tr>
		</thead>
		<tbody>
		<?php
			$lignes = '';
			foreach ($this->tabCompetences as $key=>$competence) {
				$lignes .= '<tr>';
				$lignes .= '<td>' . $competence['id_competence'] . '</td>';  
				$lignes .= '<td>' . $competence['lib_competence'] . '</td>';  
				$lignes .= '<td>' . $competence['lib_competence_principale'] . '</td>';  
				$lignes .= '<td><a type="button" href="' . $competence['linkEdit'] .'" class="btn btn-primary btn-xs">Modifier</a></td>';  
				$lignes .= '<td><a type="button" href="' . $competence['linkDel'] . '" class="btn btn-primary btn-xs">Supprimer</a></td>';  
				$lignes .= '</tr>'; 
			}
			echo $lignes;
		?>
		</tbody>
	</table>
</div>